Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Infrastructure Configuration"
        Parameters:
          - VPCId
          - EnvironmentSize
          - SSHkeyname
          - RoleForSyslog
      -  
        Label:
          default: "Syslog Configuration"
        Parameters:
          - InstallSourceTdAgent
          - SyslogBucket
          - SyslogBucketRegion
          - SyslogPrefix
          - SyslogCollectInterval
          - SyslogUploadS3Interval

Parameters:
  SyslogBucket:
    Type: String
    Default: jianyuancao-assignments-bucket
    Description: bucket for stored EC2 syslog
  SyslogBucketRegion:
    Type: String
    Default: us-east-1
    Description: Syslog bucket Region
  SyslogPrefix:
    Type: String
    Default: "syslogs/"
    Description: Prefix of the file on S3
  SyslogCollectInterval:
    Type: String
    Default: "%Y%m%d%H"
    Description: syslog collection interval hour-%Y%m%d%H, minute-%Y%m%d%H%M
    AllowedValues:
      - "%Y%m%d%H"
      - "%Y%m%d%H%M"
  SyslogUploadS3Interval:
    Type: String
    Default: 10
    Description: syslog upload to S3 interval x minutes
  InstallSourceTdAgent:
    Type: String
    Default: "curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh"
    Description: Install td-agent from fluentd
  RoleForSyslog:
    Type: String
    Default: RoleSyslogToS3Test
    Description: custom role for write syslog to S3
  VPCId:
    Type: String
    Default: vpc-23242758
    Description: custom VPC
  SSHkeyname:
    Type: AWS::EC2::KeyPair::KeyName 
    Default: assignmentCFN
    Description: SSH Key for login EC2
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S-t2.micro,M-t2.small,L-t2.medium)
Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-04351e12" #Amazon Linux AMI 2017.03
    us-east-2:
      "AMALINUX" : "ami-1c002379" #Amazon Linux AMI 2017.03
    us-west-1:
      "AMALINUX" : "ami-14b89b74" #Amazon Linux AMI 2017.03
    us-west-2:
      "AMALINUX" : "ami-11120768" #Amazon Linux AMI 2017.03
    eu-west-2:
      "AMALINUX" : "ami-0a85946e" #Amazon Linux AMI 2017.03
    eu-west-1:
      "AMALINUX" : "ami-13f7226a" #Amazon Linux AMI 2017.03
    ap-northeast-2:
      "AMALINUX" : "ami-7ee13b10" #Amazon Linux AMI 2017.03
    ap-northeast-1:
      "AMALINUX" : "ami-21815747" #Amazon Linux AMI 2017.03
    ca-central-1:
      "AMALINUX" : "ami-32bb0556" #Amazon Linux AMI 2017.03
    ap-southeast-1:
      "AMALINUX" : "ami-1926ab7a" #Amazon Linux AMI 2017.03
    ap-southeast-2:
      "AMALINUX" : "ami-42e9f921" #Amazon Linux AMI 2017.03
    eu-central-1:
      "AMALINUX" : "ami-0460cb6b" #Amazon Linux AMI 2017.03   
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
    LARGE:  
      "EC2" : "t2.medium"
  
Resources:
  RoleSyslogtoS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleForSyslog 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "S3SyslogAdmin"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "s3:*"
                Resource: "*"
  RoleSyslogtoS3Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref RoleSyslogtoS3
  EC2:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
#   CreationPolicy:
#     ResourceSignal:
#       Count: 1
#       Timeout: PT5M
    Properties:
      IamInstanceProfile: !Ref RoleSyslogtoS3Profile
      ImageId: !FindInMap [RegionMap,!Ref "AWS::Region","AMALINUX"] 
      InstanceType: !FindInMap [InstanceSize,!Ref EnvironmentSize, EC2]
      KeyName: !Ref SSHkeyname
      SecurityGroupIds: 
        - !Ref SecurityGroup 
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -ex
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets tdagent --region ${AWS::Region}
            yum -y update
           # /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2 --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          tdagent:
            - "configure_cfn"
            - "remove_NTP"
            - "install_chrony"
            - "config_OS"
            - "SyslogTotd-agent"
            - "install_td-agent"
            - "config_td-agent"
            - "restart-td-agent"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets tdagent --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub | 
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"  
        remove_NTP:
          test: "test $(rpm -qa|grep ntp)"
          commands:
            remove_ntp_packages:
              command: "yum -y remove ntp*"
        install_chrony:
          test: "test ! $(rpm -qa|grep chrony)"
          packages:
            yum:
              chrony: []
          services:
            sysvinit:
              chronyd:
                enabled: "true"
                ensureRunning: "true"
        config_OS:
          commands:
            01_increase_max_file_descriport:
              test: "test $(grep -i '#add by CFN' /etc/security/limits.conf|wc -l) -lt 1"
              command: "echo -e \"$ADD_CONTENT\" >> limits.conf"
              env: 
                ADD_CONTENT: "#add by CFN\n
                              root soft nofile 65536\n
                              root hard nofile 65536\n
                              * soft nofile 65536\n
                              * hard nofile 65536\n
                             "
              cwd: "/etc/security"
            02_apply_change: # apply limits.conf without reboot
              test: "test $(grep -i '#add by CFN' /etc/pam.d/common-session|wc -l) -lt 1"
              command: "echo -e \"$ADD_CONTENT\" >> common-session"
              env:
                ADD_CONTENT: "#add by CFN\n
                              session required pam_limits.so\n
                             "
              cwd: "/etc/pam.d"
            03_optimize_network_kernel_parameters:
              test: "test $(grep -i '#add by CFN' /etc/sysctl.conf|wc -l) -lt 1"
              command: "echo -e \"$ADD_CONTENT\" >> sysctl.conf"
              env:
                ADD_CONTENT: "#add by CFN\n
                              net.core.somaxconn = 1024\n
                              net.core.netdev_max_backlog = 5000\n
                              net.core.rmem_max = 16777216\n
                              net.core.wmem_max = 16777216\n
                              net.ipv4.tcp_wmem = 4096 12582912 16777216\n
                              net.ipv4.tcp_rmem = 4096 12582912 16777216\n
                              net.ipv4.tcp_max_syn_backlog = 8096\n
                              net.ipv4.tcp_slow_start_after_idle = 0\n
                              net.ipv4.tcp_tw_reuse = 1\n
                              net.ipv4.ip_local_port_range = 10240 65535\n
                             "
              cwd: "/etc"
            04_active_change: # active change sysctl.conf without reboot
              command: "sysctl -p"
              cwd: "/etc"
        SyslogTotd-agent:
          commands:
            syslog_forward_to_td-agent:
              test: "test $(grep -i '#add by CFN' /etc/rsyslog.conf|wc -l) -lt 1"
              command: "echo -e \"$ADD_CONTENT\" >> rsyslog.conf"
              env:
                ADD_CONTENT: "#add by CFN\n
                              *.* @127.0.0.1:42185\n
                             "
              cwd: "/etc"  
          services:
            sysvinit:
              rsyslog:
                ensureRunning: "true"
        install_td-agent:
          commands:
            install:
              test: "test ! $(rpm -qa|grep td-agent)" 
              command: !Sub |
                ${InstallSourceTdAgent}
              cwd: "~"
        config_td-agent:
          test: "test $(grep -i '#add by CFN' /etc/td-agent/td-agent.conf|wc -l) -lt 1"
          files:
            /etc/td-agent/td-agent.conf:
              content: !Sub |
                #add by CFN
                <source>
                  @type syslog
                  port 42185
                  tag system
                </source>
                <match system.**>
                  @type s3
                  s3_bucket ${SyslogBucket}
                  s3_region ${SyslogBucketRegion}
                  path ${SyslogPrefix}
                  buffer_path /var/log/td-agent/buffer
                  time_slice_format ${SyslogCollectInterval}
                  time_slice_wait ${SyslogUploadS3Interval}m
                  utc

                  buffer_chunk_limit 256m
                </match>
              mode: "00644"
              owner: root
              group: root
        restart-td-agent:
          services:
            td-agent:
              enabled: "true"
              ensureRunning: "true"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Only Open SSH port"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          ToPort: "22"
          FromPort: "22"
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: "-1"
          IpProtocol: "-1"
Outputs:
  assignmentEC2:
    Description: Access URL for assignmentEC2
    Value: !Join ["",["EC2 Public IP address: ",!GetAtt EC2.PublicIp]]
