#Parameters:
#  NameRoleForSyslog:
#   Type: String
#   Default: RoleSyslogToS3
#   Description: custom role for write syslog to S3   
#  SyslogBucket:
#    Type: String
#    Default: jianyuancao-assignments-bucket
#    Description: bucket for stored EC2 syslog
Resources:
  RoleSyslogtoS3:
    Type: AWS::IAM::Role
    Properties:
#      RoleName: !Ref NameRoleForSyslog 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "S3SyslogAdmin"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:*" 
                 # - "s3:ListBucket"
                 # - "s3:GetObject"
                 # - "s3:PutObject"
                Resource: "arn:aws:s3:::*"
  RoleSyslogtoS3Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref RoleSyslogtoS3
Outputs:
  SyslogRoleName:
    Description: syslog role Name
    Value: !Ref RoleSyslogtoS3
    Export:
      Name: sharedinf-SyslogRoleName    
  SyslogRoleProfile:
    Description: syslog role profile
    Value: !Ref RoleSyslogtoS3Profile
    Export:
      Name: sharedinf-SyslogRoleProfile    
