Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: Choose Default VPC
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Only Open SSH port"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          ToPort: "22"
          FromPort: "22"
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: "-1"
          IpProtocol: "-1"
Outputs:
  SGID:
    Description: SecurityGroup ID
    Value: !Ref  SecurityGroup
    Export:
      Name: sharedinf-SGID         