Description: "Master template that includes nested templates"
Parameters:
  testparameter:
    Type: String
    Description: test
    Default: No
    AllowedValues:
      - Yes
      - No
Resources:
  RoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateRole.yml  
      TimeoutInMinutes: 5
  KMSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateKMS.yml
        Parameters:
          Para1: test1
          Para2: test2
  BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateBucket.yml

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateEC2.yml
        Parameters:
          VPCId: 1323
          EnvironmentSize: 2323
          SSHkeyname: 2323
          InstallSourceTdAgent: 233
          SyslogCollectInterval: 23
          SyslogUploadS3Interval: 23
Outputs:
  EC2InstanceID:
    Value: !GetAtt ["EC2Stack","Outputs.InstanceID"]

      
                