Description: "Master template that includes nested templates"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Infrastructure Configuration"
        Parameters:
          - CFNTemplateS3
          - VPCId
          - EnvironmentSize
          - SSHkeyname
      -  
        Label:
          default: "Syslog Configuration"
        Parameters:
          - InstallSourceTdAgent
          - SyslogCollectInterval
          - SyslogUploadS3Interval
Parameters:
  CFNTemplateS3:
    Type: String
    Default: jianyuancao-assignment-code
    Description: A Bucket name which contains CloudFormation Template files in S3
  SyslogCollectInterval:
    Type: String
    Default: "%Y%m%d%H"
    Description: syslog collection interval Unit by Hour-%Y%m%d%H, Minute-%Y%m%d%H%M
    AllowedValues:
      - "%Y%m%d%H"
      - "%Y%m%d%H%M"
  SyslogUploadS3Interval:
    Type: Number
    Default: 10
    MinValue: 5
    MaxValue: 60
    Description: syslog upload to S3 interval between 5 and 60 minutes
  InstallSourceTdAgent:
    Type: String
    Default: "curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh"
    Description: Install td-agent from fluentd
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: Choose Default VPC
  SSHkeyname:
    Type: AWS::EC2::KeyPair::KeyName 
    Default: assignmentCFN
    Description: SSH Key for login EC2
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S-t2.micro,M-t2.small,L-t2.medium)
Mappings:
  RegionMap:
    ap-south-1: 
      "AMALINUX" : "ami-0400736b" #Amazon Linux AMI 2017.03
    eu-west-3: 
      "AMALINUX" : "ami-7bc17406" #Amazon Linux AMI 2017.03
    eu-west-2: 
      "AMALINUX" : "ami-11130775" #Amazon Linux AMI 2017.03
    eu-west-1: 
      "AMALINUX" : "ami-01ccc867" #Amazon Linux AMI 2017.03
    ap-northeast-2: 
      "AMALINUX" : "ami-8369baed" #Amazon Linux AMI 2017.03
    ap-northeast-1: 
      "AMALINUX" : "ami-10207a77" #Amazon Linux AMI 2017.03
    sa-east-1: 
      "AMALINUX" : "ami-1d660d71" #Amazon Linux AMI 2017.03
    ca-central-1: 
      "AMALINUX" : "ami-0bd66a6f" #Amazon Linux AMI 2017.03
    ap-southeast-1: 
      "AMALINUX" : "ami-3d8e325e" #Amazon Linux AMI 2017.03
    ap-southeast-2: 
      "AMALINUX" : "ami-10918173" #Amazon Linux AMI 2017.03
    eu-central-1: 
      "AMALINUX" : "ami-5b06d634" #Amazon Linux AMI 2017.03
    us-east-1: 
      "AMALINUX" : "ami-22ce4934" #Amazon Linux AMI 2017.03
    us-east-2: 
      "AMALINUX" : "ami-0d2a0e68" #Amazon Linux AMI 2017.03
    us-west-1: 
      "AMALINUX" : "ami-327f5352" #Amazon Linux AMI 2017.03
    us-west-2: 
      "AMALINUX" : "ami-463ab226" #Amazon Linux AMI 2017.03
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
    LARGE:  
      "EC2" : "t2.medium"
Resources:
  RoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${CFNTemplateS3}/GenerateRole.yml"
      #TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateRole.yml  
  KMSStack:
    DependsOn: [RoleStack]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${CFNTemplateS3}/GenerateKMS.yml"
      #TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateKMS.yml
  BucketStack:
    DependsOn: [KMSStack,RoleStack]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${CFNTemplateS3}/GenerateBucket.yml"
      #TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateBucket.yml
  EC2Stack:
    DependsOn: [BucketStack,SecurityGroupStack]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${CFNTemplateS3}/GenerateEC2.yml"
      #TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateEC2.yml
      Parameters:
        VPCId: !Ref VPCId
        EnvironmentSize: !Ref EnvironmentSize
        SSHkeyname: !Ref SSHkeyname
        InstallSourceTdAgent: !Ref InstallSourceTdAgent
        SyslogCollectInterval: !Ref SyslogCollectInterval
        SyslogUploadS3Interval: !Ref SyslogUploadS3Interval
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${CFNTemplateS3}/GenerateSecurityGroup.yml"
      #TemplateURL: https://s3.amazonaws.com/jianyuancao-assignment-code/GenerateSecurityGroup.yml
      Parameters:
        VPCId: !Ref VPCId

Outputs:
  EC2InstanceID:
    Value: !GetAtt ["EC2Stack","Outputs.InstanceID"]