Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - 
       Label:
         default: "VPC Defination"
       Parameters:
         - VPCcidr
         - VPCTagName
Parameters:
  VPCcidr:
    Type: String
    Default: 182.19.0.0/16
    Description: Specify the VPC IP range between x.x.x.x/16 and x.x.x.x/28
  VPCTagname:
    Type: String
    Default: vpc-test 
Resources:
  myvpc:
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: !Ref VPCcidr
     EnableDnsSupport: 'true'
     EnableDnsHostnames: 'true'
     InstanceTenancy: default
     Tags:
       - Key: Name
         Value: !Ref VPCTagname
Outputs:
  VPCId:
    Description: VPC Id
    Value: !Ref myvpc
  VPCCidrBlock:
    Description: VPC Cidr Block
    Value: !GetAtt myvpc.CidrBlock


